-- Insert Users
INSERT INTO users (username, email, password, role, create_at) VALUES
('admin', 'admin@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin', NOW()),
('john_writer', 'john@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'author', NOW()),
('sarah_smith', 'sarah@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'user', NOW()),
('tech_guru', 'tech@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'author', NOW()),
('travel_lover', 'travel@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'author', NOW());

-- Insert Categories (if not already added)
-- INSERT INTO categories (name, slug) VALUES 
-- ('Technology', 'technology'),
-- ('Travel', 'travel'),
-- ('Food', 'food'),
-- ('Lifestyle', 'lifestyle'),
-- ('Health', 'health'),
-- ('Business', 'business');

-- Insert Posts
INSERT INTO posts (title, content, slug, user_id, category_id, create_at, updated_at) VALUES
('Getting Started with PHP Programming', 'PHP is a widely-used server-side scripting language that has become increasingly fast and powerful over the years. Here are some basics to get you started:\r\n\r\n## What is PHP?\r\nPHP (Hypertext Preprocessor) is a server-side scripting language designed for web development but also used as a general-purpose programming language. It was created by Rasmus Lerdorf in 1994.\r\n\r\n## Setting Up PHP\r\nTo get started with PHP, you need:\r\n1. A web server (like Apache)\r\n2. PHP installed\r\n3. A database (usually MySQL)\r\n\r\nThe easiest way is to install a package like XAMPP or WAMP that bundles everything together.\r\n\r\n## Basic Syntax\r\n```php\r\n<?php\r\n  echo \"Hello, World!\";\r\n?>\r\n```\r\n\r\nPHP code is executed on the server, generating HTML that is then sent to the client. With PHP, you can create dynamic page content, collect form data, send and receive cookies, and much more.', 'getting-started-with-php-programming', 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),

('10 Must-Visit Destinations in Europe', 'Europe offers an incredible array of travel experiences. Here\'s my list of must-visit destinations based on my recent travels across the continent.\r\n\r\n## 1. Barcelona, Spain\r\nWith its stunning architecture by Gaudí, beautiful beaches, and amazing food scene, Barcelona offers something for everyone. Don\'t miss La Sagrada Familia and Park Güell.\r\n\r\n## 2. Santorini, Greece\r\nThe white-washed buildings with blue domes set against the deep blue Aegean Sea make Santorini one of the most picturesque places on Earth. Sunset in Oia is an unforgettable experience.\r\n\r\n## 3. Paris, France\r\nThe city of light remains one of the world\'s most beautiful cities. Beyond the Eiffel Tower and Louvre, explore charming neighborhoods like Montmartre and Le Marais.\r\n\r\n## 4. Venice, Italy\r\nThere\'s nowhere quite like Venice with its network of canals, magnificent architecture, and absence of cars. Get lost in its narrow streets and discover hidden gems.\r\n\r\n## 5. Prague, Czech Republic\r\nWith its preserved medieval architecture, Prague looks like something out of a fairy tale. The castle, Charles Bridge, and Old Town Square are must-sees.\r\n\r\nPlan at least two weeks if you want to visit several of these destinations in one trip. The best time to visit is either late spring or early autumn when the weather is pleasant and crowds are smaller than during peak summer months.', 'must-visit-destinations-in-europe', 5, 2, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),

('Healthy Breakfast Ideas to Start Your Day', 'Breakfast is often called the most important meal of the day, and for good reason. Here are some healthy breakfast ideas that are both nutritious and delicious.\r\n\r\n## Why Breakfast Matters\r\nEating breakfast jumpstarts your metabolism, provides essential nutrients, and helps improve concentration and performance throughout the day.\r\n\r\n## Overnight Oats\r\nOvernight oats are perfect for busy mornings. Simply mix rolled oats with milk or yogurt and let them sit in the fridge overnight. In the morning, top with fruits, nuts, and a drizzle of honey.\r\n\r\n**Recipe:**\r\n- 1/2 cup rolled oats\r\n- 1/2 cup milk or yogurt\r\n- 1 tablespoon chia seeds\r\n- Toppings: berries, banana, nuts, honey\r\n\r\n## Avocado Toast\r\nThis trendy breakfast is popular for good reason - it\'s nutritious, filling, and easily customizable.\r\n\r\n**Recipe:**\r\n- 1 slice whole grain bread, toasted\r\n- 1/2 ripe avocado, mashed\r\n- Salt, pepper, and red pepper flakes to taste\r\n- Optional toppings: poached egg, cherry tomatoes, feta cheese\r\n\r\nRemember to focus on incorporating protein, healthy fats, and complex carbohydrates into your breakfast for sustained energy throughout the morning.', 'healthy-breakfast-ideas', 3, 3, DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),

('Understanding Object-Oriented Programming in PHP', 'Object-Oriented Programming (OOP) is a powerful paradigm that can help you write more organized and reusable code in PHP. This post will cover the fundamental concepts of OOP in PHP.\r\n\r\n## Classes and Objects\r\nA class is a template or blueprint for creating objects. It defines properties (attributes) and methods (functions) that the objects will have.\r\n\r\n```php\r\nclass Car {\r\n    // Properties\r\n    public $color;\r\n    public $brand;\r\n    \r\n    // Constructor\r\n    public function __construct($color, $brand) {\r\n        $this->color = $color;\r\n        $this->brand = $brand;\r\n    }\r\n    \r\n    // Method\r\n    public function displayInfo() {\r\n        return \"This is a {$this->color} {$this->brand}.\";\r\n    }\r\n}\r\n\r\n// Creating an object\r\n$myCar = new Car(\"red\", \"Toyota\");\r\necho $myCar->displayInfo();\r\n```\r\n\r\n## Inheritance\r\nInheritance allows a class to inherit properties and methods from another class. This promotes code reusability.\r\n\r\n```php\r\nclass SportsCar extends Car {\r\n    public $topSpeed;\r\n    \r\n    public function __construct($color, $brand, $topSpeed) {\r\n        parent::__construct($color, $brand);\r\n        $this->topSpeed = $topSpeed;\r\n    }\r\n    \r\n    public function displayInfo() {\r\n        return parent::displayInfo() . \" It can go up to {$this->topSpeed} mph.\";\r\n    }\r\n}\r\n```\r\n\r\n## Encapsulation\r\nEncapsulation is about bundling data and methods together, and restricting direct access to some of an object\'s components.\r\n\r\n```php\r\nclass BankAccount {\r\n    private $balance;\r\n    \r\n    public function deposit($amount) {\r\n        $this->balance += $amount;\r\n    }\r\n    \r\n    public function getBalance() {\r\n        return $this->balance;\r\n    }\r\n}\r\n```\r\n\r\nBy using OOP in your PHP projects, you can create more maintainable, scalable, and modular code.', 'understanding-oop-in-php', 4, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

('How to Create a Budget Travel Itinerary', 'Traveling doesn\'t have to break the bank. With careful planning, you can create amazing travel experiences on a budget. Here\'s how to plan a budget-friendly itinerary.\r\n\r\n## Research Off-Season Travel\r\nTraveling during the shoulder season (just before or after peak season) can save you significant money on flights and accommodation while still providing good weather and experiences.\r\n\r\n## Accommodation Alternatives\r\nConsider options beyond traditional hotels:\r\n- Hostels (many offer private rooms if dorms aren\'t your style)\r\n- Vacation rentals through sites like Airbnb\r\n- House sitting opportunities\r\n- Couchsurfing for the adventurous\r\n\r\n## Transportation Tips\r\n- Use public transportation instead of taxis\r\n- Book flights in advance and be flexible with dates\r\n- Consider overnight trains or buses for longer distances to save on accommodation\r\n\r\n## Eating Economically\r\n- Shop at local markets and prepare some of your own meals\r\n- Eat where the locals eat, away from tourist areas\r\n- Have your main meal at lunch when prices are often lower\r\n\r\n## Free and Low-Cost Activities\r\n- Take advantage of free walking tours\r\n- Visit museums on free admission days\r\n- Explore parks and natural attractions\r\n- Look for city passes that bundle attractions\r\n\r\nRemember that some of the best travel experiences don\'t cost anything at all - watching a sunset, exploring a neighborhood on foot, or connecting with locals.', 'budget-travel-itinerary', 5, 2, DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),

('Modern CSS Techniques Every Developer Should Know', 'CSS has evolved significantly in recent years, with powerful new features that make creating complex layouts and interactions easier than ever before. Here are some modern CSS techniques that every web developer should have in their toolkit.\r\n\r\n## CSS Grid Layout\r\nCSS Grid has revolutionized the way we create two-dimensional layouts on the web.\r\n\r\n```css\r\n.container {\r\n  display: grid;\r\n  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\r\n  grid-gap: 20px;\r\n}\r\n```\r\n\r\nThis simple code creates a responsive grid that automatically adjusts the number of columns based on the container width.\r\n\r\n## CSS Custom Properties (Variables)\r\nCSS now supports native variables, making it easier to maintain consistent themes and enable dynamic styling.\r\n\r\n```css\r\n:root {\r\n  --primary-color: #3498db;\r\n  --secondary-color: #2ecc71;\r\n}\r\n\r\n.button {\r\n  background-color: var(--primary-color);\r\n}\r\n\r\n.button:hover {\r\n  background-color: var(--secondary-color);\r\n}\r\n```\r\n\r\n## CSS Flexbox\r\nFlexbox provides a more efficient way to layout, align, and distribute space among items in a container.\r\n\r\n```css\r\n.container {\r\n  display: flex;\r\n  justify-content: space-between;\r\n  align-items: center;\r\n}\r\n```\r\n\r\n## CSS Animations and Transitions\r\nCreate smooth, performant animations without JavaScript:\r\n\r\n```css\r\n.button {\r\n  transition: transform 0.3s ease;\r\n}\r\n\r\n.button:hover {\r\n  transform: scale(1.1);\r\n}\r\n```\r\n\r\nAdopting these modern CSS techniques will help you write more maintainable code and create better user experiences.', 'modern-css-techniques', 1, 1, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),

('The Ultimate Guide to Home Office Setup', 'Creating an effective home office setup has become increasingly important as remote work continues to grow. Here\'s a comprehensive guide to creating a productive workspace at home.\r\n\r\n## Choosing the Right Space\r\nIdeally, your home office should be in a quiet area with good natural light and minimal distractions. If a separate room isn\'t possible, look for a corner or nook that can be dedicated to your workspace.\r\n\r\n## Ergonomic Essentials\r\nInvesting in ergonomic furniture and equipment is crucial for your health and productivity:\r\n\r\n- **Chair**: Choose an adjustable chair with good lumbar support.\r\n- **Desk**: Your desk should allow your elbows to rest at 90 degrees when typing.\r\n- **Monitor**: Position your monitor at eye level, about an arm\'s length away.\r\n- **Keyboard and Mouse**: Consider ergonomic options that keep your wrists neutral.\r\n\r\n## Lighting Matters\r\nPoor lighting leads to eye strain and fatigue. Layer your lighting with:\r\n- Natural light (position your desk near a window if possible)\r\n- Overhead lighting\r\n- Task lighting for specific work areas\r\n\r\n## Tech Setup\r\nEssential technology for a functional home office:\r\n- Reliable high-speed internet\r\n- Computer or laptop (consider dual monitors for increased productivity)\r\n- Webcam and microphone for video calls\r\n- Surge protector and cable management solutions\r\n\r\n## Organization and Storage\r\nKeep your workspace tidy with appropriate storage solutions:\r\n- File cabinets or boxes for physical documents\r\n- Shelving for books and references\r\n- Drawer organizers for small supplies\r\n\r\nRemember that your home office should reflect your personal style while maximizing productivity. Even small improvements to your setup can lead to significant gains in comfort and efficiency.', 'home-office-setup-guide', 2, 4, DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),

('Easy Mediterranean Diet Recipes for Beginners', 'The Mediterranean diet is consistently ranked as one of the healthiest eating patterns in the world. Here are some simple recipes to help you get started with this delicious and nutritious way of eating.\r\n\r\n## What is the Mediterranean Diet?\r\nThe Mediterranean diet emphasizes:\r\n- Plenty of fruits, vegetables, and whole grains\r\n- Olive oil as the primary fat source\r\n- Moderate amounts of fish, poultry, and dairy\r\n- Limited red meat\r\n- Herbs and spices for flavor instead of salt\r\n\r\n## Greek Salad\r\nA classic starter that embodies Mediterranean flavors.\r\n\r\n**Ingredients:**\r\n- 2 large tomatoes, chopped\r\n- 1 cucumber, chopped\r\n- 1 red onion, thinly sliced\r\n- 1 bell pepper, chopped\r\n- 200g feta cheese, cubed\r\n- 1/2 cup kalamata olives\r\n- 2 tablespoons extra virgin olive oil\r\n- 1 tablespoon red wine vinegar\r\n- 1 teaspoon dried oregano\r\n- Salt and pepper to taste\r\n\r\n**Instructions:**\r\nCombine all ingredients in a large bowl, toss gently, and serve.\r\n\r\n## Simple Mediterranean Pasta\r\nA quick weeknight dinner option.\r\n\r\n**Ingredients:**\r\n- 300g whole wheat pasta\r\n- 3 tablespoons olive oil\r\n- 3 cloves garlic, minced\r\n- 1 pint cherry tomatoes, halved\r\n- 1/4 cup olives, sliced\r\n- 2 tablespoons capers\r\n- 200g fresh spinach\r\n- Juice of 1 lemon\r\n- 50g feta cheese, crumbled\r\n- Fresh basil leaves\r\n- Red pepper flakes (optional)\r\n\r\n**Instructions:**\r\n1. Cook pasta according to package directions.\r\n2. In a large pan, heat olive oil and sauté garlic until fragrant.\r\n3. Add tomatoes, olives, and capers. Cook for 3-4 minutes.\r\n4. Add spinach and cook until wilted.\r\n5. Toss with cooked pasta, lemon juice, and feta cheese.\r\n6. Garnish with fresh basil and red pepper flakes if desired.\r\n\r\nThese simple recipes make it easy to incorporate Mediterranean diet principles into your everyday cooking.', 'mediterranean-diet-recipes', 3, 3, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),

('Understanding JavaScript Promises and Async/Await', 'JavaScript\'s asynchronous programming features have evolved significantly with Promises and async/await syntax. These tools make it easier to work with asynchronous operations like API calls, file operations, and timers.\r\n\r\n## What are Promises?\r\nA Promise is an object representing the eventual completion or failure of an asynchronous operation. It\'s a proxy for a value not necessarily known when the promise is created.\r\n\r\n```javascript\r\nconst fetchData = () => {\r\n  return new Promise((resolve, reject) => {\r\n    // Simulating an API call\r\n    setTimeout(() => {\r\n      const data = { id: 1, name: \'John\' };\r\n      // Success case\r\n      resolve(data);\r\n      // Failure case would be: reject(\'Error fetching data\');\r\n    }, 2000);\r\n  });\r\n};\r\n\r\nfetchData()\r\n  .then(data => console.log(\'Data received:\', data))\r\n  .catch(error => console.error(\'Error:\', error));\r\n```\r\n\r\n## Promise Chaining\r\nPromises can be chained to handle sequences of asynchronous operations:\r\n\r\n```javascript\r\nfetchUserData(userId)\r\n  .then(userData => fetchUserPosts(userData.username))\r\n  .then(posts => console.log(posts))\r\n  .catch(error => console.error(error));\r\n```\r\n\r\n## Async/Await\r\nAsync/await is syntactic sugar built on top of Promises, making asynchronous code look and behave more like synchronous code:\r\n\r\n```javascript\r\nasync function getUserPosts(userId) {\r\n  try {\r\n    const userData = await fetchUserData(userId);\r\n    const posts = await fetchUserPosts(userData.username);\r\n    return posts;\r\n  } catch (error) {\r\n    console.error(\'Error fetching user posts:\', error);\r\n    throw error;\r\n  }\r\n}\r\n\r\n// Usage\r\ngetUserPosts(1)\r\n  .then(posts => console.log(posts))\r\n  .catch(error => console.error(error));\r\n```\r\n\r\n## Promise.all for Parallel Operations\r\nWhen you need to run multiple async operations in parallel:\r\n\r\n```javascript\r\nasync function getMultipleData() {\r\n  try {\r\n    const [users, posts, comments] = await Promise.all([\r\n      fetchUsers(),\r\n      fetchPosts(),\r\n      fetchComments()\r\n    ]);\r\n    return { users, posts, comments };\r\n  } catch (error) {\r\n    console.error(\'One of the requests failed\', error);\r\n    throw error;\r\n  }\r\n}\r\n```\r\n\r\nMastering Promises and async/await is essential for writing clean, maintainable asynchronous JavaScript code, especially in modern web development.', 'javascript-promises-async-await', 4, 1, DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),

('Tips for Maintaining a Healthy Work-Life Balance', 'In today\'s always-connected world, maintaining a healthy work-life balance is more challenging and more important than ever. Here are practical strategies to help you achieve better balance and well-being.\r\n\r\n## Set Clear Boundaries\r\nEstablish clear work hours and stick to them. Let colleagues know when you\'re available and when you\'re not.\r\n\r\n- Create a designated workspace that you can leave behind at the end of the workday\r\n- Set up separate work and personal devices if possible\r\n- Turn off work notifications after hours\r\n\r\n## Prioritize Your Time\r\nNot all tasks are created equal. Focus on what truly matters:\r\n\r\n- Use the Eisenhower Matrix to categorize tasks by urgency and importance\r\n- Learn to say no to low-priority requests\r\n- Delegate tasks when appropriate\r\n\r\n## Schedule Downtime\r\nDowntime shouldn\'t be an afterthought—it should be part of your schedule:\r\n\r\n- Block time for family, hobbies, and self-care in your calendar\r\n- Take your vacation days and truly disconnect\r\n- Schedule short breaks throughout your workday\r\n\r\n## Practice Mindfulness\r\nBeing present can help reduce stress and increase enjoyment of both work and personal time:\r\n\r\n- Take a few minutes each day for meditation or deep breathing\r\n- Practice single-tasking rather than multitasking\r\n- Create transition rituals between work and personal time\r\n\r\n## Regular Exercise and Sleep\r\nPhysical well-being is foundational to maintaining balance:\r\n\r\n- Aim for at least 30 minutes of moderate exercise most days\r\n- Prioritize 7-8 hours of quality sleep\r\n- Consider a morning workout to boost energy and productivity\r\n\r\nRemember that work-life balance looks different for everyone, and it can change throughout different life stages. The key is finding what works for you and being willing to adjust as needed.', 'work-life-balance-tips', 2, 4, DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY));

-- Insert Comments
INSERT INTO comments (content, post_id, user_id, created_at) VALUES
('This is a great introduction to PHP! I\'ve been looking to get started with PHP programming and this gives me a good roadmap to follow.', 1, 3, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Could you recommend any good books or online courses for further learning PHP?', 1, 5, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Thanks for the response! I\'ll definitely check out those resources.', 1, 5, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('I\'ve visited Barcelona and Santorini from your list and they are absolutely stunning! Can\'t wait to visit the others.', 2, 1, DATE_SUB(NOW(), INTERVAL 9 DAY)),
('I would add Budapest to this list. It\'s an underrated gem with beautiful architecture and affordable prices.', 2, 3, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('I\'ve been making overnight oats for breakfast and it\'s been a game-changer for my morning routine! So quick and customizable.', 3, 5, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('Great explanation of OOP concepts! The examples make it much easier to understand.', 4, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('I\'ve been coding in PHP for years but never properly understood inheritance until reading this post. Thanks!', 4, 3, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('These budget travel tips are so practical! I used similar strategies when backpacking through Europe last year and saved a ton of money.', 5, 2, DATE_SUB(NOW(), INTERVAL 14 DAY)),
('CSS Grid has completely changed how I approach layouts. No more float hacks!', 6, 4, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('I just set up my home office following these guidelines and it\'s made such a difference in my productivity. Especially the lighting tips!', 7, 3, DATE_SUB(NOW(), INTERVAL 19 DAY)),
('That Greek salad recipe is delicious! I added some fresh mint and it took it to another level.', 8, 1, DATE_SUB(NOW(), INTERVAL 7 DAY)),
('This clarified promises for me finally! I\'ve been struggling with asynchronous JavaScript for a while.', 9, 2, DATE_SUB(NOW(), INTERVAL 11 DAY)),
('Setting boundaries has been the most important change I\'ve made for my work-life balance. It was hard at first but so worth it.', 10, 4, DATE_SUB(NOW(), INTERVAL 17 DAY)),
('I\'ve found that scheduling specific downtime in my calendar works really well - if it\'s scheduled, I\'m more likely to actually take the break.', 10, 5, DATE_SUB(NOW(), INTERVAL 15 DAY));